// country_list source : https://gist.github.com/darryl-snow/3820279
export default {
"Country1":"Afghanistan",
"Country2":"Albania",
"Country3":"Algeria",
"Country4":"Andorra",
"Country5":"Angola",
"Country6":"Anguilla",
"Country7":"Antigua &amp; Barbuda",
"Country8":"Argentina",
"Country9":"Armenia",
"Country10":"Aruba",
"Country11":"Australia",
"Country12":"Austria",
"Country13":"Azerbaijan",
"Country14":"Bahamas",
"Country15":"Bahrain",
"Country16":"Bangladesh",
"Country17":"Barbados",
"Country18":"Belarus",
"Country19":"Belgium",
"Country20":"Belize",
"Country21":"Benin",
"Country22":"Bermuda",
"Country23":"Bhutan",
"Country24":"Bolivia",
"Country25":"Bosnia &amp; Herzegovina",
"Country26":"Botswana",
"Country27":"Brazil",
"Country28":"British Virgin Islands",
"Country29":"Brunei",
"Country30":"Bulgaria",
"Country31":"Burkina Faso",
"Country32":"Burundi",
"Country33":"Cambodia",
"Country34":"Cameroon",
"Country35":"Cape Verde",
"Country36":"Cayman Islands",
"Country37":"Chad",
"Country38":"Chile",
"Country39":"China",
"Country40":"Colombia",
"Country41":"Congo",
"Country42":"Cook Islands",
"Country43":"Costa Rica",
"Country44":"Cote D Ivoire",
"Country45":"Croatia",
"Country46":"Cruise Ship",
"Country47":"Cuba",
"Country48":"Cyprus",
"Country49":"Czech Republic",
"Country50":"Denmark",
"Country51":"Djibouti",
"Country52":"Dominica",
"Country53":"Dominican Republic",
"Country54":"Ecuador",
"Country55":"Egypt",
"Country56":"El Salvador",
"Country57":"Equatorial Guinea",
"Country58":"Estonia",
"Country59":"Ethiopia",
"Country60":"Falkland Islands",
"Country61":"Faroe Islands",
"Country62":"Fiji",
"Country63":"Finland",
"Country64":"France",
"Country65":"French Polynesia",
"Country66":"French West Indies",
"Country67":"Gabon",
"Country68":"Gambia",
"Country69":"Georgia",
"Country70":"Germany",
"Country71":"Ghana",
"Country72":"Gibraltar",
"Country73":"Greece",
"Country74":"Greenland",
"Country75":"Grenada",
"Country76":"Guam",
"Country77":"Guatemala",
"Country78":"Guernsey",
"Country79":"Guinea",
"Country80":"Guinea Bissau",
"Country81":"Guyana",
"Country82":"Haiti",
"Country83":"Honduras",
"Country84":"Hong Kong",
"Country85":"Hungary",
"Country86":"Iceland",
"Country87":"India",
"Country88":"Indonesia",
"Country89":"Iran",
"Country90":"Iraq",
"Country91":"Ireland",
"Country92":"Isle of Man",
"Country93":"Israel",
"Country94":"Italy",
"Country95":"Jamaica",
"Country96":"Japan",
"Country97":"Jersey",
"Country98":"Jordan",
"Country99":"Kazakhstan",
"Country100":"Kenya",
"Country101":"Kuwait",
"Country102":"Kyrgyz Republic",
"Country103":"Laos",
"Country104":"Latvia",
"Country105":"Lebanon",
"Country106":"Lesotho",
"Country107":"Liberia",
"Country108":"Libya",
"Country109":"Liechtenstein",
"Country110":"Lithuania",
"Country111":"Luxembourg",
"Country112":"Macau",
"Country113":"Macedonia",
"Country114":"Madagascar",
"Country115":"Malawi",
"Country116":"Malaysia",
"Country117":"Maldives",
"Country118":"Mali",
"Country119":"Malta",
"Country120":"Mauritania",
"Country121":"Mauritius",
"Country122":"Mexico",
"Country123":"Moldova",
"Country124":"Monaco",
"Country125":"Mongolia",
"Country126":"Montenegro",
"Country127":"Montserrat",
"Country128":"Morocco",
"Country129":"Mozambique",
"Country130":"Namibia",
"Country131":"Nepal",
"Country132":"Netherlands",
"Country133":"Netherlands Antilles",
"Country134":"New Caledonia",
"Country135":"New Zealand",
"Country136":"Nicaragua",
"Country137":"Niger",
"Country138":"Nigeria",
"Country139":"Norway",
"Country140":"Oman",
"Country141":"Pakistan",
"Country142":"Palestine",
"Country143":"Panama",
"Country144":"Papua New Guinea",
"Country145":"Paraguay",
"Country146":"Peru",
"Country147":"Philippines",
"Country148":"Poland",
"Country149":"Portugal",
"Country150":"Puerto Rico",
"Country151":"Qatar",
"Country152":"Reunion",
"Country153":"Romania",
"Country154":"Russia",
"Country155":"Rwanda",
"Country156":"Saint Pierre &amp; Miquelon",
"Country157":"Samoa",
"Country158":"San Marino",
"Country159":"Satellite",
"Country160":"Saudi Arabia",
"Country161":"Senegal",
"Country162":"Serbia",
"Country163":"Seychelles",
"Country164":"Sierra Leone",
"Country165":"Singapore",
"Country166":"Slovakia",
"Country167":"Slovenia",
"Country168":"South Africa",
"Country169":"South Korea",
"Country170":"Spain",
"Country171":"Sri Lanka",
"Country172":"St Kitts &amp; Nevis",
"Country173":"St Lucia",
"Country174":"St Vincent",
"Country175":"St. Lucia",
"Country176":"Sudan",
"Country177":"Suriname",
"Country178":"Swaziland",
"Country179":"Sweden",
"Country180":"Switzerland",
"Country181":"Syria",
"Country182":"Taiwan",
"Country183":"Tajikistan",
"Country184":"Tanzania",
"Country185":"Thailand",
"Country186":"Timor L'Este",
"Country187":"Togo",
"Country188":"Tonga",
"Country189":"Trinidad &amp; Tobago",
"Country190":"Tunisia",
"Country191":"Turkey",
"Country192":"Turkmenistan",
"Country193":"Turks &amp; Caicos",
"Country194":"Uganda",
"Country195":"Ukraine",
"Country196":"United Arab Emirates",
"Country197":"United Kingdom",
"Country198":"Uruguay",
"Country199":"Uzbekistan",
"Country200":"Venezuela",
"Country201":"Vietnam",
"Country202":"Virgin Islands (US)",
"Country203":"Yemen",
"Country204":"Zambia",
"Country205":"Zimbabwe"
}
